name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - run: sudo apt-get update && sudo apt-get install fakeroot

    - name: Run a one-line script
      run: fakeroot ./build-deb.sh
